# Generated by Django 4.2.16 on 2024-11-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=100)),
                ('favorite_color', models.CharField(max_length=50)),
                ('preferred_season', models.CharField(max_length=50)),
                ('arrangement_style', models.CharField(blank=True, max_length=100, null=True)),
                ('bouquet_size', models.CharField(blank=True, max_length=50, null=True)),
                ('occasion', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_scent', models.CharField(blank=True, max_length=100, null=True)),
                ('special_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
